services:
  challenge:
    image: ctf-nc-file:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "11337:1337"
    environment:
      FLAG: "flag{this_is_a_sample_flag}"