services:
  challenge:
    image: ctf-web-rust:latest
    build: .
    restart: unless-stopped
    # volumes:
    #   - ./static:/var/www/html
    environment:
      # BIND_ADDR: 0.0.0.0:80
      # STATIC_PATH: /var/www/html
      FLAG: flag{test_flag}
    ports:
      - "8000:80"
